version: '3.7'

services:
        web_server:
                container_name: cm_nginx
                build:
                        #location of dockerfile
                        context: ./nginx
                ports:
                        - 8081:80
                depends_on:
                        - app
        app:
                container_name: cm_flask
                build:
                        #location of dockerfile
                        context: ./python
                env_file: postgres/database.conf
                ports:
                        - 8000:8000
                depends_on:
                        - database
             
        database:
                container_name: cm_postgres
                image: postgres:latest
                env_file: postgres/database.conf
                ports:
                        - 5434:5432
                
